### ISSUE TITLE
move_and_resize

### ISSUE THREAD

**Issue by rCarto** [riatelab/mapinsetr#5]
work on the intersection thing

**Comment by rCarto** [comment]
https://github.com/r-spatial/sf/issues/1088

**Comment by Bakaniko** [comment]
As I first bring the issue, I think I can at least be involved here.

I didn't look at `move_and_resize()` so I didn't know it does an intersection (and that intersection will change the column order).

So the idea is to make sure that  `move_and_resize()` returns columns in the same order ?

**Comment by rCarto** [comment]
commit https://github.com/riatelab/mapinsetr/commit/3cb49bbe213c80c00c534ca66805691b5d9df1d4 should take care of that.

**Comment by Bakaniko** [comment]
Tested with the problematic data : issue fixed.
Thanks
